package jp.codex.earthquakeoverlay;

import android.app.*; import android.content.*; import android.graphics.Color; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.provider.Settings; import android.text.*; import android.text.style.ForegroundColorSpan; import android.view.*; import android.widget.*; import org.json.*; import java.io.*; import java.net.*; import java.util.*; import java.util.concurrent.*;

public class OverlayService extends Service {
    public static final String TEST_ACTION="jp.codex.earthquakeoverlay.TEST"; public static final String TEST_LATEST_ACTION="jp.codex.earthquakeoverlay.TEST_LATEST"; static final int NOTIFY=7;
    Handler h=new Handler(Looper.getMainLooper()); ScheduledExecutorService worker; WindowManager wm; TextView banner; String lastId=""; ArrayList<CharSequence> pages=new ArrayList<>(); int pageIndex;
    @Override public void onCreate(){super.onCreate(); channel(); startForeground(NOTIFY,notification()); IntentFilter f=new IntentFilter(); f.addAction(TEST_ACTION); f.addAction(TEST_LATEST_ACTION); registerReceiver(testReceiver,f,Context.RECEIVER_NOT_EXPORTED); if(Settings.canDrawOverlays(this)) createOverlay(); worker=Executors.newSingleThreadScheduledExecutor(); worker.scheduleAtFixedRate(this::poll,2,30,TimeUnit.SECONDS);}
    BroadcastReceiver testReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(TEST_LATEST_ACTION.equals(i.getAction())){worker.submit(()->poll(true));return;} ArrayList<CharSequence> p=new ArrayList<>(); SpannableStringBuilder s=new SpannableStringBuilder("表示テスト\n自宅地域 "); int a=s.length(); s.append("震度1"); s.setSpan(new ForegroundColorSpan(Color.YELLOW),a,s.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE); s.append("　PC入力の上に表示中"); p.add(s); showPages(p,true);}};
    void createOverlay(){ if(banner!=null)return; wm=(WindowManager)getSystemService(WINDOW_SERVICE); banner=new TextView(this); banner.setTextColor(Color.WHITE); banner.setTextSize(17); banner.setGravity(Gravity.CENTER_VERTICAL); banner.setPadding(dp(24),dp(5),dp(24),dp(5)); banner.setMaxLines(2); banner.setLineSpacing(0,1.0f); banner.setVisibility(View.GONE); banner.setElevation(20); WindowManager.LayoutParams p=new WindowManager.LayoutParams(-1,dp(82),Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS, -3); p.gravity=Gravity.TOP; wm.addView(banner,p); }
    void poll(){poll(false);}
    void poll(boolean force){ try{String s=get("https://api.p2pquake.net/v2/jma/quake?limit=5"); JSONArray a=new JSONArray(s); if(a.length()==0)return; JSONObject root=a.getJSONObject(0); JSONObject q=root.optJSONObject("earthquake"); if(q==null)return; String id=q.optString("time")+q.optString("hypocenter"); if(!force&&id.equals(lastId))return; JSONArray pts=root.optJSONArray("points"); int home=-1, other=-1; String pref=getPreferences().getString("pref",""); String city=getPreferences().getString("city",""); ArrayList<Region> regions=new ArrayList<>();
        int detail=getPreferences().getInt("detail",1); LinkedHashMap<String,Region> grouped=new LinkedHashMap<>(); for(int i=0;pts!=null&&i<pts.length();i++){JSONObject p=pts.getJSONObject(i); int sc=p.optInt("scale",-1); if(sc<10)continue; String prefName=p.optString("pref",""); String addr=p.optString("addr",""); String full=prefName+addr; boolean isHome=(!pref.isEmpty()&&full.contains(pref))||(!city.isEmpty()&&full.contains(city)); if(isHome)home=Math.max(home,sc); else other=Math.max(other,sc); String name=detail==0?prefName:(detail==1?municipality(addr):full); Region old=grouped.get(name); if(old==null||sc>old.scale)grouped.put(name,new Region(name,sc,isHome)); else if(isHome)old.home=true;} regions.addAll(grouped.values());
        if(force||home>=10||other>=30){if(!force)lastId=id; Collections.sort(regions,(x,y)->Integer.compare(y.scale,x.scale)); JSONObject hp=q.optJSONObject("hypocenter"); String place=hp==null?"":hp.optString("name",""); int max=Math.max(q.optInt("maxScale",-1),Math.max(home,other));
            ArrayList<CharSequence> out=new ArrayList<>();
            SpannableStringBuilder page1=new SpannableStringBuilder("地震情報"); out.add(page1);
            SpannableStringBuilder page2=new SpannableStringBuilder(place+"\n最大震度 "); int ma=page2.length(); page2.append(scale(max)); page2.setSpan(new ForegroundColorSpan(scaleColor(max)),ma,page2.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE); page2.append("　M").append(String.valueOf(hp==null?0:hp.optDouble("magnitude",0))).append("\n津波の心配："); String tsunami=q.optString("domesticTsunami","Unknown"); int ta=page2.length(); page2.append(tsunamiLabel(tsunami)); page2.setSpan(new ForegroundColorSpan(tsunamiColor(tsunami)),ta,page2.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE); out.add(page2);
            for(int start=0;start<regions.size();start+=3){SpannableStringBuilder page=new SpannableStringBuilder("各地の震度\n"); int end=Math.min(start+3,regions.size()); for(int j=start;j<end;j++){if(j>start)page.append("　"); Region r=regions.get(j); if(r.home)page.append("自宅 "); page.append(r.name).append(" "); int begin=page.length(); page.append("震度").append(scale(r.scale)); page.setSpan(new ForegroundColorSpan(scaleColor(r.scale)),begin,page.length(),Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);} out.add(page);} showPages(out,false);}
    }catch(Exception ignored){} }
    static class Region {String name; int scale; boolean home; Region(String n,int s,boolean h){name=n;scale=s;home=h;}}
    String municipality(String a){java.util.regex.Matcher m=java.util.regex.Pattern.compile("^(.+?(?:市|区|町|村))").matcher(a); return m.find()?m.group(1):a;}
    String scale(int x){return x==45?"5弱":x==50?"5強":x==55?"6弱":x==60?"6強":x==70?"7":String.valueOf(Math.max(1,x/10));}
    int scaleColor(int x){return x>=60?Color.RED:x>=45?Color.rgb(255,145,0):x>=30?Color.YELLOW:Color.rgb(90,210,255);}
    String tsunamiLabel(String x){return "None".equalsIgnoreCase(x)?"なし":("Warning".equalsIgnoreCase(x)||"Watch".equalsIgnoreCase(x)||"MajorWarning".equalsIgnoreCase(x))?"あり":"調査中";}
    int tsunamiColor(String x){return "None".equalsIgnoreCase(x)?Color.rgb(120,230,150):(tsunamiLabel(x).equals("調査中")?Color.YELLOW:Color.RED);}
    SharedPreferences getPreferences(){return getSharedPreferences("settings",0);}
    String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("User-Agent","EarthquakeOverlay/1.0");try(InputStream in=c.getInputStream();BufferedReader r=new BufferedReader(new InputStreamReader(in,"UTF-8"))){StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}finally{c.disconnect();}}
    void showPages(ArrayList<CharSequence> p,boolean test){ if(banner==null&&Settings.canDrawOverlays(this))createOverlay(); if(banner==null)return; h.post(()->{pages=p;pageIndex=0; GradientDrawable g=new GradientDrawable();g.setColor(test?0xC82D5AA0:0xB8000000);g.setCornerRadius(dp(6));banner.setBackground(g);banner.setText(pages.get(0),TextView.BufferType.SPANNABLE);banner.setVisibility(View.VISIBLE); h.removeCallbacks(hide); h.removeCallbacks(pageTick); h.postDelayed(pageTick,5000);});}
    Runnable pageTick=new Runnable(){public void run(){if(banner!=null&&banner.getVisibility()==View.VISIBLE&&!pages.isEmpty()){if(pageIndex+1>=pages.size()){hide.run();}else{pageIndex++; banner.setText(pages.get(pageIndex),TextView.BufferType.SPANNABLE); h.postDelayed(this,5000);}}}};
    Runnable hide=()->{if(banner!=null)banner.setVisibility(View.GONE);h.removeCallbacks(pageTick);}; int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    void channel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("earthquake","地震テロップ",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    Notification notification(){return new Notification.Builder(this,"earthquake").setContentTitle("地震テロップ").setContentText("地震情報を監視中").setSmallIcon(android.R.drawable.ic_dialog_info).setOngoing(true).build();}
    @Override public int onStartCommand(Intent i,int f,int id){if(banner==null&&Settings.canDrawOverlays(this))createOverlay();return START_STICKY;}
    @Override public void onDestroy(){try{unregisterReceiver(testReceiver);}catch(Exception ignored){}if(worker!=null)worker.shutdownNow();if(banner!=null)wm.removeView(banner);super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}
}
