package jp.codex.earthquakeoverlay;

import android.content.*; import android.net.Uri; import android.os.*; import android.provider.Settings; import androidx.core.content.FileProvider; import org.json.*; import java.io.*; import java.net.*; import java.util.regex.*;

public final class UpdateManager {
    static final String API="https://api.github.com/repos/hayato41200/android-tv-earthquake-overlay/releases/latest";
    public interface Callback { void result(boolean available,String tag); }
    public static void check(Context context,Callback cb){ new Thread(()->{try{JSONObject r=new JSONObject(get(API)); String tag=r.optString("tag_name",""); boolean newer=version(tag)>version("v"+BuildConfig.VERSION_NAME); context.getSharedPreferences("update",0).edit().putLong("checked",System.currentTimeMillis()).putBoolean("available",newer).putString("tag",tag).putString("url",assetUrl(r)).apply(); cb.result(newer,tag);}catch(Exception e){cb.result(context.getSharedPreferences("update",0).getBoolean("available",false),context.getSharedPreferences("update",0).getString("tag",""));}}).start(); }
    public static void checkIfDue(Context c,Callback cb){if(System.currentTimeMillis()-c.getSharedPreferences("update",0).getLong("checked",0)>21600000L)check(c,cb);else cb.result(c.getSharedPreferences("update",0).getBoolean("available",false),c.getSharedPreferences("update",0).getString("tag",""));}
    public static void downloadAndInstall(Context c){new Thread(()->{try{String u=c.getSharedPreferences("update",0).getString("url","");if(u.isEmpty())return;File dir=new File(c.getCacheDir(),"updates");dir.mkdirs();File apk=new File(dir,"app-release.apk");HttpURLConnection x=(HttpURLConnection)new URL(u).openConnection();x.setRequestProperty("User-Agent","EarthquakeOverlay/1.0");try(InputStream in=x.getInputStream();OutputStream out=new FileOutputStream(apk)){byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);}finally{x.disconnect();}Intent i=new Intent(Intent.ACTION_VIEW,FileProvider.getUriForFile(c,c.getPackageName()+".fileprovider",apk));i.setDataAndType(FileProvider.getUriForFile(c,c.getPackageName()+".fileprovider",apk),"application/vnd.android.package-archive");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);c.startActivity(i);}catch(Exception ignored){}}).start();}
    public static void openInstallPermission(Context c){if(Build.VERSION.SDK_INT>=26&&!c.getPackageManager().canRequestPackageInstalls())c.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+c.getPackageName())));}
    static String assetUrl(JSONObject r)throws Exception{JSONArray a=r.optJSONArray("assets");return a==null||a.length()==0?"":a.getJSONObject(0).optString("browser_download_url","");}
    static int version(String s){Matcher m=Pattern.compile("(\\d+)\\.(\\d+)(?:\\.(\\d+))?").matcher(s);return m.find()?Integer.parseInt(m.group(1))*10000+Integer.parseInt(m.group(2))*100+(m.group(3)==null?0:Integer.parseInt(m.group(3))):0;}
    static String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setRequestProperty("User-Agent","EarthquakeOverlay/1.0");try(InputStream in=c.getInputStream();BufferedReader r=new BufferedReader(new InputStreamReader(in,"UTF-8"))){StringBuilder b=new StringBuilder();String l;while((l=r.readLine())!=null)b.append(l);return b.toString();}finally{c.disconnect();}}
}
